## Chapter 8 Python与数据分析

### 8.1 数据清洗与规则

#### 8.1.1 缺失值处理

In [1]:
import pandas as pd
import numpy as np
from numpy import nan as NA

In [2]:
data1 = pd.Series([1, NA, None])
data1

0    1.0
1    NaN
2    NaN
dtype: float64

In [3]:
data1.isnull()

0    False
1     True
2     True
dtype: bool

In [4]:
data2 = pd.DataFrame(np.random.exponential(1, size = (5, 3)))
data2.iloc[2:, 0] = NA
data2.iloc[1] = NA
data2

         0         1         2
0  2.07884  0.426632  1.783478
1      NaN       NaN       NaN
2      NaN  0.605696  0.413180
3      NaN  0.937157  1.618883
4      NaN  0.954613  0.262703

In [5]:
data2.fillna(1)

         0         1         2
0  2.07884  0.426632  1.783478
1  1.00000  1.000000  1.000000
2  1.00000  0.605696  0.413180
3  1.00000  0.937157  1.618883
4  1.00000  0.954613  0.262703

In [6]:
data2.mean()

0    2.078840
1    0.731024
2    1.019561
dtype: float64

In [7]:
data2.fillna(data2.mean())

         0         1         2
0  2.07884  0.426632  1.783478
1  2.07884  0.731024  1.019561
2  2.07884  0.605696  0.413180
3  2.07884  0.937157  1.618883
4  2.07884  0.954613  0.262703

In [8]:
data2.fillna({0: 1.1, 1: 1.2, 2: 1.3})

         0         1         2
0  2.07884  0.426632  1.783478
1  1.10000  1.200000  1.300000
2  1.10000  0.605696  0.413180
3  1.10000  0.937157  1.618883
4  1.10000  0.954613  0.262703

In [9]:
data2.fillna(method = 'ffill')

         0         1         2
0  2.07884  0.426632  1.783478
1  2.07884  0.426632  1.783478
2  2.07884  0.605696  0.413180
3  2.07884  0.937157  1.618883
4  2.07884  0.954613  0.262703

In [10]:
data2.fillna(method = 'bfill', axis = 1, limit = 1, inplace = True)
data2

          0         1         2
0  2.078840  0.426632  1.783478
1       NaN       NaN       NaN
2  0.605696  0.605696  0.413180
3  0.937157  0.937157  1.618883
4  0.954613  0.954613  0.262703

In [11]:
data3 = pd.Series([NA, NA, 1, 2, NA])
data3[data3.notnull()]

2    1.0
3    2.0
dtype: float64

In [12]:
data3.dropna()

2    1.0
3    2.0
dtype: float64

In [13]:
data4 = pd.DataFrame(np.random.gamma(1, 1, size = (4, 3)))
data4.iloc[1:, 0] = NA
data4.iloc[2] = NA
data4

          0         1         2
0  0.175501  0.458449  0.702009
1       NaN  0.104751  0.143943
2       NaN       NaN       NaN
3       NaN  1.431890  2.199054

In [14]:
data4.dropna()

          0         1         2
0  0.175501  0.458449  0.702009

In [15]:
data4.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [16]:
data4.dropna(how = 'all')

          0         1         2
0  0.175501  0.458449  0.702009
1       NaN  0.104751  0.143943
3       NaN  1.431890  2.199054

In [17]:
data5  = pd.DataFrame({'name': ['C. Ronaldo', 'Messi'] * 3,
                     'Number': [4, 5, 5, 5, 5, 5]})
data5

         name  Number
0  C. Ronaldo       4
1       Messi       5
2  C. Ronaldo       5
3       Messi       5
4  C. Ronaldo       5
5       Messi       5

In [18]:
data5.duplicated()

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool

In [20]:
data5.drop_duplicates()

         name  Number
0  C. Ronaldo       4
1       Messi       5
2  C. Ronaldo       5

In [21]:
data5.drop_duplicates('name')

         name  Number
0  C. Ronaldo       4
1       Messi       5

#### 8.1.2 异常值处理

In [26]:
data6 = pd.DataFrame([[1, 2, 99999, 4], [66666, 6, 7, 8]])
data6

       0  1      2  3
0      1  2  99999  4
1  66666  6      7  8

In [23]:
data6.replace([99999, 66666], NA, inplace = True)
data6

     0  1    2  3
0  1.0  2  NaN  4
1  NaN  6  7.0  8

In [27]:
data6.replace({99999: 3, 66666: 5})

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [131]:
df = pd.DataFrame(np.random.randn(500, 3))

In [132]:
df.describe()

                0           1           2
count  500.000000  500.000000  500.000000
mean    -0.021335    0.024877   -0.017627
std      1.016469    1.013151    1.019504
min     -2.974913   -2.628384   -3.015256
25%     -0.696495   -0.628723   -0.697976
50%      0.028588   -0.004326    0.002614
75%      0.643429    0.686360    0.613223
max      2.859043    3.367535    3.635751

In [171]:
outliers = df.copy()
mean = df.mean()
std = df.std()
for col in df.columns:
    outliers[col] = (df[col] > mean[col] + std[col] * 3) | (df[col] < mean[col] - std[col] * 3)

In [181]:
df[outliers.any(1)]

            0         1         2
23  -0.198013  0.257465  3.146985
65   0.953057 -0.509374  3.635751
119 -0.674823  0.886395  3.313335
207  0.348026  3.367535  0.324092
322 -0.102322  3.075968  0.582024

In [185]:
df[outliers] = 3 * np.sign(df)

#### 8.1.3 索引操作

In [28]:
ex = pd.Series([True, False, False], index = ['d', 'c', 'a'])
ex

d     True
c    False
a    False
dtype: bool

In [29]:
ex.reindex(['a', 'b', 'c', 'd'])

a    False
b      NaN
c    False
d     True
dtype: object

In [30]:
philosophers = pd.read_csv("..\examples\ex1.csv")
philosophers

        name  birthyear  country  num_of_discussions_on_zhihu
0       Marx       1818  Germany                            0
1       Kant       1724  Germany                          635
2  Nietzsche       1844  Germany                          472
3      Camus       1913   French                          203
4      Hegel       1770  Germany                          358

In [31]:
philosophers.reindex(index = range(6), columns = ['name', 'country'])

        name  country
0       Marx  Germany
1       Kant  Germany
2  Nietzsche  Germany
3      Camus   French
4      Hegel  Germany
5        NaN      NaN

In [198]:
philosophers.set_index('name')

           birthyear  country  num_of_discussions_on_zhihu
name
Marx            1818  Germany                            0
Kant            1724  Germany                          635
Nietzsche       1844  Germany                          472
Camus           1913   French                          203
Hegel           1770  Germany                          358

In [199]:
philosophers.set_index('name').reset_index()

        name  birthyear  country  num_of_discussions_on_zhihu
0       Marx       1818  Germany                            0
1       Kant       1724  Germany                          635
2  Nietzsche       1844  Germany                          472
3      Camus       1913   French                          203
4      Hegel       1770  Germany                          358

In [242]:
index = [['A'] * 3 + ['B'] * 3 + ['C'] * 3, ['i', 'ii','iii'] * 3]
mulidx_ser = pd.Series(np.random.randn(9), index = index)
mulidx_ser

A  i     -1.869462
   ii     1.251899
   iii   -0.056493
B  i     -1.016995
   ii    -0.100035
   iii   -0.550948
C  i     -0.038153
   ii    -0.614913
   iii   -0.557901
dtype: float64

In [243]:
mulidx_ser.unstack()

          i        ii       iii
A -1.869462  1.251899 -0.056493
B -1.016995 -0.100035 -0.550948
C -0.038153 -0.614913 -0.557901

In [271]:
index = [['A', 'A', 'B', 'B', 'C', 'C'], ['i', 'ii'] * 3]
columns = [['Red', 'Red', 'Blue'], ['SU', 'PRC', 'US']]
mulidx_df = pd.DataFrame(np.random.randint(0, 10, size = [6, 3]), 
                         index = index, columns = columns)
mulidx_df.index.names = ['key1', 'key2']
mulidx_df.columns.names = ['level1', 'level2']
mulidx_df

level1    Red     Blue
level2     SU PRC   US
key1 key2
A    i      8   2    9
     ii     5   1    1
B    i      6   4    3
     ii     5   3    1
C    i      5   6    8
     ii     5   4    8

In [278]:
mulidx_df['Red', 'SU']

key1  key2
A     i       8
      ii      5
B     i       6
      ii      5
C     i       5
      ii      5
Name: (Red, SU), dtype: int32

In [276]:
mulidx_df.loc['C']['Blue']

level2  US
key2
i        8
ii       8

In [286]:
mulidx_df.mean(level = 0, axis = 1)

level1     Red  Blue
key1 key2
A    i     5.0   9.0
     ii    3.0   1.0
B    i     5.0   3.0
     ii    4.0   1.0
C    i     5.5   8.0
     ii    4.5   8.0

In [285]:
mulidx_df.mean(level = 1)

level1       Red                Blue
level2        SU       PRC        US
key2
i       6.333333  4.000000  6.666667
ii      5.000000  2.666667  3.333333

### 8.2 数据分组与聚合

#### 8.2.1 数据分组

In [11]:
df = pd.DataFrame({'data': np.random.randint(0, 10, size = 5),
                  'key1': ['A', 'B', 'B', 'A', 'A'],
                   'key2': ['a'] * 2 + ['b'] * 3})

In [12]:
df

   data key1 key2
0     6    A    a
1     3    B    a
2     9    B    b
3     5    A    b
4     6    A    b

In [9]:
df.groupby('key1')

In [13]:
df.groupby('key1').median()

      data
key1
A        6
B        6

In [17]:
df.groupby(['key1', 'key2']).std()

               data
key1 key2
A    a          NaN
     b     0.707107
B    a          NaN
     b          NaN

In [19]:
key3 = ['T', 'T', 'P', 'T', 'P']
df.groupby(key3).median()

   data
P   7.5
T   5.0

In [30]:
mapping = {0: 'T', 1: 'T', 2: 'P', 3: 'T', 4: 'P'}
df.groupby(mapping).median()

   data
P   7.5
T   5.0

In [24]:
index = [['A'] * 3 + ['B'] * 3 + ['C'] * 3, ['i', 'ii','iii'] * 3]
mulidx_ser = pd.DataFrame(np.random.randn(9, 2), index = index)
mulidx_ser.index.names = ['One', 'Two']

In [25]:
mulidx_ser

                0         1
One Two
A   i    0.536286  0.673222
    ii   1.675523  1.271635
    iii  1.537859 -0.191202
B   i   -0.468710 -0.952110
    ii  -1.511902 -0.244453
    iii  0.421239  0.644322
C   i    0.823737 -0.102166
    ii   1.465475  1.104126
    iii  1.238129 -0.207927

In [27]:
mulidx_ser.groupby(level = 'One').median()

            0         1
One
A    1.537859  0.673222
B   -0.468710 -0.244453
C    1.238129 -0.102166

In [29]:
mulidx_ser.groupby(level = 1).median()

            0         1
Two
i    0.536286 -0.102166
ii   1.465475  1.104126
iii  1.238129 -0.191202

In [33]:
for group_name, group_data in df.groupby('key1'):
    print(group_name)
    print(group_data)

A
   data key1 key2
0     6    A    a
3     5    A    b
4     6    A    b
B
   data key1 key2
1     3    B    a
2     9    B    b

In [35]:
for (name1, name2), group_data in df.groupby(['key1', 'key2']):
    print((name1, name2))
    print(group_data)

('A', 'a')
   data key1 key2
0     6    A    a
('A', 'b')
   data key1 key2
3     5    A    b
4     6    A    b
('B', 'a')
   data key1 key2
1     3    B    a
('B', 'b')
   data key1 key2
2     9    B    b

#### 8.2.2 数据聚合

In [36]:
df

   data key1 key2
0     6    A    a
1     3    B    a
2     9    B    b
3     5    A    b
4     6    A    b

In [49]:
def ske(arr):
    return arr.skew()

In [50]:
df.groupby('key1').aggregate(ske)

          data
key1
A    -1.732051
B          NaN

In [53]:
df.groupby('key1').aggregate(['median', len])

       data
     median len
key1
A         6   3
B         6   2

In [60]:
complex_df = pd.DataFrame(np.random.randn(5, 2))

In [67]:
grouped_df = complex_df.groupby(['T'] * 3 + ['P'] * 2)
grouped_df.agg([('MAX', max), ('MIN', min)])

          0                   1
        MAX       MIN       MAX       MIN
P  0.078491 -1.382014  1.711902 -0.014309
T  0.717691 -0.701828  0.685542 -0.151888

### 8.3 时间序列

#### 8.3.1 Python时间数据类型

In [7]:
import datetime

In [ ]:
rightnow = datetime.time(20, 20, 20)
today = datetime.date(2020, 2, 2)
now = datetime.datetime.now()

In [9]:
rightnow

datetime.time(20, 20, 20)

In [5]:
today

datetime.date(2020, 2, 2)

In [11]:
now

datetime.datetime(2020, 2, 2, 20, 20, 20)

In [12]:
delta_t = datetime.datetime(2020, 2, 17, 8, 0, 0) - now
delta_t

datetime.timedelta(days=14, seconds=41980)

In [14]:
delta_t.days

14

In [15]:
delta_t.seconds

41980

In [17]:
now + 2 * datetime.timedelta(days = 365, seconds = 3600)

datetime.datetime(2022, 2, 1, 22, 20, 20)

In [18]:
str(now)

'2020-02-02 20:20:20'

In [19]:
now.strftime("%Y%m%d")

'20200202'

In [26]:
str_time = "2020/02/02"
datetime.datetime.strptime(str_time, "%Y/%m/%d")

datetime.datetime(2020, 2, 2, 0, 0)

In [35]:
pd.to_datetime("2019-12-31 23:59:59")

Timestamp('2019-12-31 23:59:59')

In [47]:
pd.to_datetime("Dec 31, 2019 11:59 pm")

Timestamp('2019-12-31 23:59:00')

In [50]:
pd.to_datetime("2019#12#31#23#59#59", format = "%Y#%m#%d#%H#%M#%S")

Timestamp('2019-12-31 23:59:59')

#### 8.3.2 时间序列的构建

In [54]:
date_str = ["2019-12-21", "2019-12-26", "2019-12-31",
            "2020-1-5", "2020-1-10"]
date_index = pd.to_datetime(date_str)

In [56]:
time_series = pd.Series(np.random.randn(5).cumsum(), index = date_index)
time_series

2019-12-21   -0.844619
2019-12-26   -0.949743
2019-12-31   -0.597782
2020-01-05   -0.059789
2020-01-10    0.757202
dtype: float64

In [57]:
time_series.index

DatetimeIndex(['2019-12-21', '2019-12-26', '2019-12-31', '2020-01-05',
               '2020-01-10'],
              dtype='datetime64[ns]', freq=None)

In [63]:
 pd.date_range("2020-1-1", periods = 1000, freq = '7D')

DatetimeIndex(['2020-01-01', '2020-01-08', '2020-01-15', '2020-01-22',
               '2020-01-29', '2020-02-05', '2020-02-12', '2020-02-19',
               '2020-02-26', '2020-03-04',
               ...
               '2038-12-22', '2038-12-29', '2039-01-05', '2039-01-12',
               '2039-01-19', '2039-01-26', '2039-02-02', '2039-02-09',
               '2039-02-16', '2039-02-23'],
              dtype='datetime64[ns]', length=1000, freq='7D')

In [69]:
time_series[datetime.datetime(2020, 1, 5)]

-0.05978908476221312

In [64]:
time_series['2020-1-5']

-0.05978908476221312

In [70]:
time_series['20200105']

-0.05978908476221312

In [71]:
time_series['2019']

2019-12-21   -0.844619
2019-12-26   -0.949743
2019-12-31   -0.597782
dtype: float64

In [72]:
time_series['2020-1']

2020-01-05   -0.059789
2020-01-10    0.757202
dtype: float64

In [73]:
time_series['20191230': '20200105']

2019-12-31   -0.597782
2020-01-05   -0.059789
dtype: float64

In [74]:
time_series.shift(2) # 前移两位

2019-12-21         NaN
2019-12-26         NaN
2019-12-31   -0.844619
2020-01-05   -0.949743
2020-01-10   -0.597782
dtype: float64

In [75]:
time_series.shift(-1)  # 后移一位

2019-12-21   -0.949743
2019-12-26   -0.597782
2019-12-31   -0.059789
2020-01-05    0.757202
2020-01-10         NaN
dtype: float64

In [77]:
time_series / time_series.shift(1) - 1  # 计算变化率

2019-12-21          NaN
2019-12-26     0.124463
2019-12-31    -0.370585
2020-01-05    -0.899982
2020-01-10   -13.664558
dtype: float64

In [45]:
period = pd.Period('2020-02', freq = 'M')
period

Period('2020-02', 'M')

In [46]:
period + 2

Period('2020-04', 'M')

In [47]:
pd.Period('2020-4', 'M') - period

2

In [51]:
pd.period_range('2019-12-01', '2020-02-02', freq = '7D')

PeriodIndex(['2019-12-01', '2019-12-08', '2019-12-15', '2019-12-22',
             '2019-12-29', '2020-01-05', '2020-01-12', '2020-01-19',
             '2020-01-26', '2020-02-02'],
            dtype='period[7D]', freq='7D')

In [55]:
period_str = ['2019Q3', '2019Q4', '2020Q1']
pd.PeriodIndex(period_str, freq =  "Q")

PeriodIndex(['2019Q3', '2019Q4', '2020Q1'], dtype='period[Q-DEC]', freq='Q-DEC')

In [56]:
year = [2019] * 4 + [2020] * 4
quarter = [1, 2, 3, 4] * 2
pd.PeriodIndex(year = year, quarter = quarter)

PeriodIndex(['2019Q1', '2019Q2', '2019Q3', '2019Q4', '2020Q1', '2020Q2',
             '2020Q3', '2020Q4'],
            dtype='period[Q-DEC]', freq='Q-DEC')

In [60]:
index = pd.to_datetime(['31/12/2019', '01/01/2020', '29/02/2020'])
time_series1 = pd.Series(np.random.randn(3).cumsum(), index = index)
time_series1

2019-12-31    1.042095
2020-01-01    2.293800
2020-02-29    1.811781
dtype: float64

In [63]:
time_series2 = time_series1.to_period(freq = 'M')
time_series2

2019-12    1.042095
2020-01    2.293800
2020-02    1.811781
Freq: M, dtype: float64

In [64]:
time_series2.to_timestamp()

2019-12-01    1.042095
2020-01-01    2.293800
2020-02-01    1.811781
Freq: MS, dtype: float64

In [65]:
time_series2.to_timestamp(how = 'end')

2019-12-31    1.042095
2020-01-31    2.293800
2020-02-29    1.811781
Freq: M, dtype: float64

In [66]:
time_series2.asfreq('D')

2019-12-31    1.042095
2020-01-31    2.293800
2020-02-29    1.811781
Freq: D, dtype: float64

In [72]:
time_series2.asfreq('A-DEC')

2019    1.042095
2020    2.293800
2020    1.811781
Freq: A-DEC, dtype: float64

In [80]:
p = pd.Period('2020-01', freq = 'M')
p.asfreq('A-DEC')

Period('2020', 'A-DEC')

In [89]:
time_series1.asfreq('BMS')

2020-01-01    2.2938
2020-02-03       NaN
Freq: BMS, dtype: float64

In [90]:
time_series2.asfreq('A-DEC')

2019    1.042095
2020    2.293800
2020    1.811781
Freq: A-DEC, dtype: float64

In [ ]:
period_index = pd.period_range('2018-08', '2020-02', freq = 'M')

In [99]:
period_index.asfreq('D', how = 'start')

PeriodIndex(['2018-08-01', '2018-09-01', '2018-10-01', '2018-11-01',
             '2018-12-01', '2019-01-01', '2019-02-01', '2019-03-01',
             '2019-04-01', '2019-05-01', '2019-06-01', '2019-07-01',
             '2019-08-01', '2019-09-01', '2019-10-01', '2019-11-01',
             '2019-12-01', '2020-01-01', '2020-02-01'],
            dtype='period[D]', freq='D')

In [102]:
period_index.asfreq('D', how = 'end')

PeriodIndex(['2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30',
             '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31',
             '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31',
             '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30',
             '2019-12-31', '2020-01-31', '2020-02-29'],
            dtype='period[D]', freq='D')

#### 8.3.3 重新采样

In [114]:
index = pd.date_range('2020-02-01', periods = 12, freq = '15min')
ts = pd.Series(np.random.randn(12), index = index)
ts

2020-02-01 00:00:00   -0.082735
2020-02-01 00:15:00    1.078822
2020-02-01 00:30:00   -1.373518
2020-02-01 00:45:00   -0.129805
2020-02-01 01:00:00    0.693018
2020-02-01 01:15:00    0.153265
2020-02-01 01:30:00    2.457777
2020-02-01 01:45:00    0.346136
2020-02-01 02:00:00    1.605658
2020-02-01 02:15:00   -0.569654
2020-02-01 02:30:00   -1.781733
2020-02-01 02:45:00   -1.401524
Freq: 15T, dtype: float64

In [118]:
ts.resample('H').sum()

2020-02-01 00:00:00   -0.507236
2020-02-01 01:00:00    3.650196
2020-02-01 02:00:00   -2.147254
Freq: H, dtype: float64

In [110]:
ts.resample('H', how = 'mean')

2020-01-31    0.031041
2020-02-29   -0.115940
2020-03-31   -0.227346
2020-04-30    0.003778
Freq: M, dtype: float64

In [121]:
ts.resample('H').max()

2020-02-01 00:00:00    1.078822
2020-02-01 01:00:00    2.457777
2020-02-01 02:00:00    1.605658
Freq: H, dtype: float64

In [126]:
ts.resample('H', label = 'right').ohlc()

                         open      high       low     close
2020-02-01 01:00:00 -0.082735  1.078822 -1.373518 -0.129805
2020-02-01 02:00:00  0.693018  2.457777  0.153265  0.346136
2020-02-01 03:00:00  1.605658  1.605658 -1.781733 -1.401524